package com.winter.demo.dao;

import com.winter.demo.entity.LoginUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    LoginUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    int updateByPrimaryKey(LoginUser record);

    List<LoginUser> queryByLoginUser(LoginUser loginUser);
}