package com.winter.demo.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class LoginUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_name
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.create_time
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.salt
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_name
     *
     * @return the value of user_login.user_name
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_name
     *
     * @param userName the value for user_login.user_name
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password
     *
     * @return the value of user_login.password
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password
     *
     * @param password the value for user_login.password
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.create_time
     *
     * @return the value of user_login.create_time
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.create_time
     *
     * @param createTime the value for user_login.create_time
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.salt
     *
     * @return the value of user_login.salt
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.salt
     *
     * @param salt the value for user_login.salt
     *
     * @mbggenerated Sun Dec 09 14:29:43 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}